from __future__ import annotations

import logging
import os
from datetime import UTC, datetime
from zoneinfo import ZoneInfo

from flask import Flask, jsonify, render_template, request

from config.settings import AppSettings
from dashboard.data_service import DashboardDataService
from dashboard.scan_job_service import ScanJobService
from dashboard.simulator_service import DashboardSimulatorService
from storage.supabase_postgres_repository import SupabasePostgresRepository


def _texts(lang: str) -> dict[str, str]:
    en = {
        "title": "Stock Scanner Dashboard",
        "run_again": "Run Again",
        "status": "Status",
        "scan_job": "Scan Job",
        "job_status": "Job Status",
        "job_phase": "Phase",
        "job_progress": "Progress",
        "job_current_ticker": "Current Ticker",
        "job_logs": "Live Logs",
        "job_running_msg": "Job is already running",
        "filter": "Filter",
        "all": "All",
        "summary": "Latest Run Summary",
        "sort": "Sort",
        "sort_score": "Score",
        "sort_setup": "Setup Quality",
        "sort_entry": "Entry Timing",
        "sort_momentum": "Momentum",
        "sort_rs": "Relative Strength",
        "sort_highs": "Distance from Highs",
        "timeframe": "Widget Timeframe",
        "tf_d": "Daily (d)",
        "tf_w": "Weekly (w)",
        "tf_m": "Monthly (m)",
        "no_run": "No previous scan result was found yet. Click Run Again to create the first run.",
        "market_widgets": "Market Widgets",
        "details": "Explanation and signals",
        "col_ticker": "Ticker",
        "col_price": "Current Price",
        "col_score": "Setup Score",
        "col_setup": "Setup Quality",
        "col_entry_timing": "Entry Timing",
        "col_class": "Classification",
        "col_buyability": "Buyability",
        "col_entry": "Suggested Entry",
        "col_stop": "Risk Stop",
        "col_target": "First Target",
        "col_rr": "Reward/Risk",
        "col_sector": "Sector",
        "col_signals": "Signals Detected",
        "help_ticker": "Symbol of the stock. Click to open TradingView.",
        "help_price": "Latest closing price from the most recent scan date.",
        "help_score": "Composite score combining trend strength, momentum, volume confirmation and relative strength.",
        "help_setup": "Pure setup quality score, independent of current entry timing.",
        "help_entry_timing": "Entry timing score based on extension, support/resistance, and reward-to-risk.",
        "help_class": "BUY, WATCH, or AVOID based on score thresholds.",
        "help_buyability": "Actionability label for whether this setup is buyable now or should be waited on.",
        "help_entry": "Indicative entry level from the trade planner.",
        "help_stop": "Stop loss level; ATR-based when ATR is available.",
        "help_target": "Initial upside target for the setup.",
        "help_rr": "Projected reward-to-risk ratio from entry to first target vs stop.",
        "help_sector": "GICS sector used for diversification checks.",
        "help_signals": "Machine-readable reasons generated by the scoring engine.",
        "visual_signals": "Visual Signals",
        "component_scores": "Component Scores",
        "main_features": "Main Features",
        "apply": "Apply",
        "stocks_analyzed": "S&P 500 stocks analyzed",
        "simulator": "Simulator",
        "simulator_title": "Paper Trading Simulator",
        "sim_market": "Market Status",
        "market_open": "Market is OPEN",
        "market_closed": "Market is CLOSED",
        "sim_status": "Simulator Status",
        "sim_cash": "Cash",
        "sim_equity": "Total Equity",
        "sim_realized": "Realized P&L",
        "sim_unrealized": "Unrealized P&L",
        "sim_open_positions": "Open Positions",
        "sim_last_update": "Last Update",
        "sim_run_id": "Run ID",
        "sim_actions": "Activity Feed",
        "sim_positions": "Open Positions Table",
        "sim_equity_curve": "Equity Curve",
        "tick_now": "Tick Now",
        "sim_wait_market": "The simulator is waiting for market hours to resume",
        "sim_no_positions": "No open positions yet",
        "sim_no_trades": "No trades executed yet",
        "time_col": "Time",
        "symbol_col": "Symbol",
        "action_col": "Action Taken",
        "shares_col": "Shares",
        "exec_price_col": "Execution Price",
        "expl_col": "Explanation",
        "cash_bal_col": "Cash Balance",
        "port_val_col": "Portfolio Value",
        "pnl_pct_col": "Unrealized P&L %",
        "pos_status_col": "Status",
    }
    he = {
        "title": "לוח סריקת מניות",
        "run_again": "הרץ שוב",
        "status": "סטטוס",
        "scan_job": "משימת סריקה",
        "job_status": "סטטוס משימה",
        "job_phase": "שלב",
        "job_progress": "התקדמות",
        "job_current_ticker": "סימול נוכחי",
        "job_logs": "לוגים חיים",
        "job_running_msg": "המשימה כבר רצה",
        "filter": "סינון",
        "all": "הכל",
        "summary": "סיכום הריצה האחרונה",
        "sort": "מיון",
        "sort_score": "ציון",
        "sort_setup": "איכות סטאפ",
        "sort_entry": "תזמון כניסה",
        "sort_momentum": "מומנטום",
        "sort_rs": "חוזק יחסי",
        "sort_highs": "מרחק מהשיא",
        "timeframe": "טווח זמן לווידג׳ט",
        "tf_d": "יומי (d)",
        "tf_w": "שבועי (w)",
        "tf_m": "חודשי (m)",
        "no_run": "לא נמצאו תוצאות סריקה קודמות. לחץ על הרץ שוב כדי להתחיל.",
        "market_widgets": "ווידג׳טים של מדדי שוק",
        "details": "הסבר ואינדיקציות",
        "col_ticker": "מניה",
        "col_price": "מחיר נוכחי",
        "col_score": "ציון הזדמנות",
        "col_setup": "איכות סטאפ",
        "col_entry_timing": "תזמון כניסה",
        "col_class": "סיווג",
        "col_buyability": "סטטוס קניה",
        "col_entry": "מחיר כניסה",
        "col_stop": "סטופ לוס",
        "col_target": "יעד ראשון",
        "col_rr": "יחס סיכוי/סיכון",
        "col_sector": "סקטור",
        "col_signals": "אינדיקציות טכניות",
        "help_ticker": "סמל המניה. לחיצה תפתח את TradingView.",
        "help_price": "מחיר הסגירה האחרון מתאריך הסריקה.",
        "help_score": "ציון משוקלל שמבוסס על מגמה, מומנטום, נפח וחוזק יחסי.",
        "help_setup": "ציון איכות טכני של הסטאפ, ללא תלות בתזמון הכניסה הנוכחי.",
        "help_entry_timing": "ציון תזמון הכניסה לפי מתיחה, תמיכה/התנגדות ויחס סיכוי/סיכון.",
        "help_class": "BUY / WATCH / AVOID לפי ספי הדירוג.",
        "help_buyability": "האם הסטאפ מתאים לקניה עכשיו או שעדיף להמתין.",
        "help_entry": "מחיר כניסה מומלץ לפי מנוע התכנון.",
        "help_stop": "רמת סטופ לוס המבוססת על ATR כאשר זמין.",
        "help_target": "יעד רווח ראשון עבור הסטאפ.",
        "help_rr": "יחס סיכוי/סיכון בין יעד ראשון לסטופ.",
        "help_sector": "סקטור המניה לצורך בקרת ריכוזיות.",
        "help_signals": "סיבות מכונה שהופקו ממנוע הדירוג.",
        "visual_signals": "איתותים ויזואליים",
        "component_scores": "ציוני רכיבים",
        "main_features": "מאפיינים מרכזיים",
        "apply": "החל",
        "stocks_analyzed": "מניות S&P 500 שנותחו",
        "simulator": "סימולטור",
        "simulator_title": "סימולטור מסחר דמה",
        "sim_market": "סטטוס שוק",
        "market_open": "השוק פתוח",
        "market_closed": "השוק סגור",
        "sim_status": "סטטוס סימולטור",
        "sim_cash": "מזומן",
        "sim_equity": "שווי תיק",
        "sim_realized": "רווח/הפסד ממומש",
        "sim_unrealized": "רווח/הפסד לא ממומש",
        "sim_open_positions": "פוזיציות פתוחות",
        "sim_last_update": "עדכון אחרון",
        "sim_run_id": "מזהה ריצה",
        "sim_actions": "יומן פעולות",
        "sim_positions": "טבלת פוזיציות פתוחות",
        "sim_equity_curve": "עקומת הון",
        "tick_now": "רענון החלטות",
        "sim_wait_market": "הסימולטור ממתין לחידוש שעות המסחר",
        "sim_no_positions": "אין עדיין פוזיציות פתוחות",
        "sim_no_trades": "עדיין לא בוצעו עסקאות",
        "time_col": "זמן",
        "symbol_col": "סימול",
        "action_col": "פעולה",
        "shares_col": "כמות מניות",
        "exec_price_col": "מחיר ביצוע",
        "expl_col": "הסבר",
        "cash_bal_col": "יתרת מזומן",
        "port_val_col": "שווי תיק",
        "pnl_pct_col": "רווח/הפסד %",
        "pos_status_col": "סטטוס",
    }
    return he if lang == "he" else en


def create_app() -> Flask:
    """Create and configure the local dashboard Flask app."""
    app = Flask(__name__, template_folder="templates", static_folder="static")
    app.secret_key = os.environ.get("FLASK_SECRET_KEY", "local-dashboard-dev-key")

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    )

    settings = AppSettings()
    logging.getLogger("DashboardApp").info(
        "Boot settings: save_to_supabase=%s output_dir=%s",
        settings.save_to_supabase,
        settings.output_dir,
    )
    settings.ensure_directories()
    supabase_repository = SupabasePostgresRepository(
        db_url=settings.supabase_db_url if settings.save_to_supabase else None,
    )
    if settings.save_to_supabase:
        supabase_repository.healthcheck()
    data_service = DashboardDataService(settings=settings, supabase_repository=supabase_repository)
    scan_job_service = ScanJobService(settings=settings)
    simulator_service = DashboardSimulatorService(
        settings=settings,
        data_service=data_service,
        supabase_repository=supabase_repository,
    )
    market_tz = ZoneInfo("America/New_York")

    @app.template_filter("currency")
    def currency(value: object) -> str:
        if value is None or value == "":
            return "-"
        return f"${float(value):,.2f}"

    @app.template_filter("number")
    def number(value: object) -> str:
        if value is None or value == "":
            return "-"
        return f"{float(value):,.2f}"

    @app.template_filter("pct")
    def pct(value: object) -> str:
        if value is None or value == "":
            return "-"
        return f"{float(value) * 100.0:,.2f}%"

    @app.template_filter("et_time")
    def et_time(value: object) -> str:
        if value in (None, "", "-"):
            return "-"
        if isinstance(value, datetime):
            dt = value
        else:
            text = str(value).replace("Z", "+00:00")
            try:
                dt = datetime.fromisoformat(text)
            except ValueError:
                return str(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=UTC)
        et = dt.astimezone(market_tz)
        return et.strftime("%Y-%m-%d %I:%M:%S %p ET")

    @app.get("/")
    def index() -> str:
        job_status = scan_job_service.status()
        status = job_status.get("status", "idle")
        error_message = job_status.get("error")

        lang = request.args.get("lang", "en").lower()
        if lang not in {"en", "he"}:
            lang = "en"

        selected_classification = request.args.get("classification", "ALL").upper()
        sort_by = request.args.get("sort_by", "score")
        widget_tf = request.args.get("widget_tf", "d").lower()
        if widget_tf not in {"d", "w", "m"}:
            widget_tf = "d"

        run = data_service.load_latest_run(lang=lang, sort_by=sort_by, widget_tf=widget_tf)
        rows: list[dict] = []
        if run is not None:
            rows = run["rows"]
            if selected_classification in {"BUY", "WATCH", "AVOID"}:
                rows = [row for row in rows if row.get("classification", "").upper() == selected_classification]

        return render_template(
            "index.html",
            t=_texts(lang),
            lang=lang,
            dir="rtl" if lang == "he" else "ltr",
            status=status,
            error_message=error_message,
            job_status=job_status,
            selected_classification=selected_classification,
            sort_by=sort_by,
            widget_tf=widget_tf,
            run=run,
            rows=rows,
        )

    @app.get("/simulator")
    def simulator() -> str:
        lang = request.args.get("lang", "en").lower()
        if lang not in {"en", "he"}:
            lang = "en"
        snapshot = simulator_service.snapshot()
        return render_template(
            "simulator.html",
            t=_texts(lang),
            lang=lang,
            dir="rtl" if lang == "he" else "ltr",
            sim=snapshot,
        )

    @app.post("/simulator/tick")
    def simulator_tick() -> tuple[dict, int]:
        snapshot = simulator_service.tick()
        return jsonify(snapshot), 200

    @app.get("/health")
    def health() -> tuple[dict, int]:
        return jsonify({"status": "ok"}), 200

    @app.post("/run-again")
    def run_again() -> tuple[dict, int]:
        started, message = scan_job_service.start()
        code = 202 if started else 409
        return (
            jsonify(
                {
                    "started": started,
                    "message": message,
                    "status": scan_job_service.status(),
                }
            ),
            code,
        )

    @app.get("/run-status")
    def run_status() -> tuple[dict, int]:
        return jsonify(scan_job_service.status()), 200

    return app


app = create_app()


if __name__ == "__main__":
    app.run(
        debug=os.environ.get("FLASK_DEBUG", "0") == "1",
        host=os.environ.get("HOST", "0.0.0.0"),
        port=int(os.environ.get("PORT", "5000")),
    )
